<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-378FNKH" failures="3" tests="3" name="Default test(failed)" time="8.064" errors="0" timestamp="2024-06-20T18:39:53 IST">
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUserByName" time="3.463">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.testDeleteUserByName(DataDrivenTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUserByName" time="1.161">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.testDeleteUserByName(DataDrivenTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUserByName" time="1.155">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DataDrivenTests.testDeleteUserByName(DataDrivenTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="0.0">
    <ignored/>
  </testcase> <!-- testPostUser -->
</testsuite> <!-- Default test(failed) -->
